
 
import java.awt.Color;
import java.awt.Dimension; 
import java.awt.Toolkit;
import java.awt.Window;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
 import java.sql.Statement;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
 
import java.sql.CallableStatement;
import java.sql.Types;
import javax.swing.JOptionPane;
import javax.swing.*; 
import java.util.Date;
import java.text.SimpleDateFormat;  
import java.text.DateFormat;  
import java.text.Format;  
import java.util.Calendar;  

 
 
/**
 *
 * @author Chameleon
 */
public class MainMenu extends javax.swing.JFrame implements Runnable{
    SimpleDateFormat timeFormat;
    String time;
     boolean x=false;
    static String driverClassName="oracle.jdbc.OracleDriver";
    static String url = "jdbc:oracle:thin:@192.168.6.21:1521/dblabs";
    static Connection dbConnection = null;
    static Connection dbConnection2 = null;
    static Connection dbConnection3 = null;
    static String username = "it175093";
    static String passwd = "Powerteam1515"; 
    String todayUpdated ;

   
    public MainMenu()
    {      
        initComponents(); 
        centreWindow(this);
        Thread t=new Thread(this);
        t.start(); 
        changeMovie();
    }
   
    void changeMovie()
    
    {
             timeFormat = new SimpleDateFormat("HH:mm:ss");      
             time=timeFormat.format(Calendar.getInstance().getTime());
             int timezone = Integer.parseInt(time.substring(0,2));
             Format f = new SimpleDateFormat("EEEE");  
             String today = f.format(new Date());  
             if(today.equals("Κυριακή")){ today="Sunday"; }
             else if(today.equals("Δευτέρα")){ today="Monday"; }
             else if(today.equals("Τρίτη")){ today="Tuesday"; }
             else if(today.equals("Τετάρτη")){ today="Wednesday"; }
             else if(today.equals("Πέμπτη")){ today="Thursday"; }
             else if(today.equals("Παρασκευή")){ today="Friday"; }
             else if(today.equals("Σάββατο")){ today="Saturday"; }
            try{     
              dbConnection3= DriverManager.getConnection(url,username,passwd);
               CallableStatement  insertSchedule= dbConnection3.prepareCall("{call  changeMovie(?,?,?)}"); 
               insertSchedule.setInt(1,timezone);
               insertSchedule.setString(2,today);
               insertSchedule.registerOutParameter(3, Types.VARCHAR);
               insertSchedule.executeUpdate();
               todayUpdated=insertSchedule.getString(3);
               String todayUpdated2 = String.valueOf(todayUpdated);
                  if(todayUpdated2.equals("null"))
                  {
                      todayUpdated2= "advertisements";
                  }
              todayUpdated2= todayUpdated2.toUpperCase();
              movieText.setText(todayUpdated2);
                  
                
           }catch(SQLException ex)
             {
                 
                 while(ex != null){
                 System.out.println("\n -- SQL Exception -- \n" + ex.getMessage());
                 ex=ex.getNextException();
             
              }
           }
                  

    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WeeklyProgramBUTTON = new javax.swing.JButton();
        NewCustomerButton = new javax.swing.JButton();
        TimelineInsertionButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();
        liveNow = new javax.swing.JTextField();
        animatedText = new javax.swing.JPanel();
        movieText = new javax.swing.JLabel();
        timeText = new javax.swing.JLabel();
        insertMovie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WindowOpen(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(141, 194, 190));
        jPanel1.setFocusCycleRoot(true);

        WeeklyProgramBUTTON.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        WeeklyProgramBUTTON.setText("Weekly TV Schedule");
        WeeklyProgramBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeeklyProgramBUTTONActionPerformed(evt);
            }
        });

        NewCustomerButton.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        NewCustomerButton.setText("New Customer");
        NewCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCustomerButtonActionPerformed(evt);
            }
        });

        TimelineInsertionButton.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        TimelineInsertionButton.setText("Insert in Timeline");
        TimelineInsertionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimelineInsertionButtonActionPerformed(evt);
            }
        });

        EditButton.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        EditButton.setText("Entries / Modification");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        AboutButton.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        AboutButton.setText("About");
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });

        liveNow.setEditable(false);
        liveNow.setBackground(new java.awt.Color(255, 51, 51));
        liveNow.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        liveNow.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        liveNow.setText("LIVE NOW");
        liveNow.setToolTipText("");
        liveNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liveNowActionPerformed(evt);
            }
        });

        movieText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        movieText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        timeText.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout animatedTextLayout = new javax.swing.GroupLayout(animatedText);
        animatedText.setLayout(animatedTextLayout);
        animatedTextLayout.setHorizontalGroup(
            animatedTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, animatedTextLayout.createSequentialGroup()
                .addComponent(timeText, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addGap(78, 78, 78)
                .addComponent(movieText, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        animatedTextLayout.setVerticalGroup(
            animatedTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movieText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(timeText, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        insertMovie.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        insertMovie.setText("Register a movie");
        insertMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertMovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(animatedText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TimelineInsertionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(AboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(283, 283, 283))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(liveNow, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(WeeklyProgramBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(liveNow, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(animatedText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60)
                .addComponent(WeeklyProgramBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(NewCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insertMovie, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TimelineInsertionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(AboutButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Centered page
    public static void centreWindow(Window frame)
    {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();  
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
        
    }  
    

    
    
  
    
    private void WeeklyProgramBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeeklyProgramBUTTONActionPerformed
            WeeklyProgramPage weeklyProgram = new WeeklyProgramPage();
            weeklyProgram.setVisible(true);
            this.hide();
    }//GEN-LAST:event_WeeklyProgramBUTTONActionPerformed
    
    
    private void liveNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liveNowActionPerformed
       
       
        
    }//GEN-LAST:event_liveNowActionPerformed

    private void NewCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCustomerButtonActionPerformed
      
        
        NewCustomerMenu program = new NewCustomerMenu();             
        program.setVisible(true);       
        this.hide();
     
    }//GEN-LAST:event_NewCustomerButtonActionPerformed

    private void TimelineInsertionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimelineInsertionButtonActionPerformed
        InsertionTimelinePage insertionTimeline = new InsertionTimelinePage();
        insertionTimeline.setVisible(true);
        this.hide();
    }//GEN-LAST:event_TimelineInsertionButtonActionPerformed

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
        About about = new About();
        about.setVisible(true);
        this.hide();
    }//GEN-LAST:event_AboutButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        EditPage editPage = new  EditPage();
        editPage.setVisible(true);
        this.hide();
    }//GEN-LAST:event_EditButtonActionPerformed

    private void WindowOpen(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowOpen
            
         Thread animation = new Thread(new Runnable() {
             @Override
             public void run() {
              
                while(true)
                {                                 
                   if((x==false)){
                    liveNow.setBackground(Color.black);
                    liveNow.setForeground(Color.red);
                    x=true;
                } else{
                    liveNow.setBackground(Color.red);
                    liveNow.setForeground(Color.black);
                   
                    x=false;
                }
                   
                    try {
                        Thread.sleep(1700);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                 
              }
             
           }
              
       });
          
             
        
         animation.start();
    }//GEN-LAST:event_WindowOpen

    private void insertMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertMovieActionPerformed
         movieInsertion insertmovie = new movieInsertion();
         this.hide();
         insertmovie.show();
    }//GEN-LAST:event_insertMovieActionPerformed

   
    public static void main(String args[]) {
        
          
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
              
            }
        });
    }
   

    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton NewCustomerButton;
    private javax.swing.JButton TimelineInsertionButton;
    private javax.swing.JButton WeeklyProgramBUTTON;
    private javax.swing.JPanel animatedText;
    private javax.swing.JButton insertMovie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField liveNow;
    private javax.swing.JLabel movieText;
    private javax.swing.JLabel timeText;
    // End of variables declaration//GEN-END:variables

 
        


    @Override
    public void run() 
    {
          while(true)
          {
                timeFormat = new SimpleDateFormat("HH:mm:ss");      
                time=timeFormat.format(Calendar.getInstance().getTime());
                timeText.setText(time);
          try {
                  Thread.sleep(1000);
              } catch (InterruptedException ex) {
                  Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
              }
          
           }    
    }
   
}






